# ============================================================
#  Netby Risk Service - Perfil Producción (prod)
#  Activo en build de producción: mvn package -Dquarkus.profile=prod
# ============================================================

quarkus.log.level=INFO
quarkus.log.category."com.netby.banking".level=INFO
