# ============================================================
#  Netby Risk Service - Configuración Común
#  Aplicada en todos los perfiles (dev, prod)
# ============================================================

quarkus.application.name=netby-risk-service
quarkus.grpc.server.port=9000
quarkus.grpc.server.host=0.0.0.0

# HTTP port (health checks / OpenAPI)
quarkus.http.port=8081
