# ============================================================
#  Netby Risk Service - Perfil Desarrollo (dev)
#  Activo por defecto con: mvn quarkus:dev
# ============================================================

quarkus.log.level=DEBUG
quarkus.log.category."com.netby.banking".level=DEBUG
